# Generated by Django 2.2.2 on 2019-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190619_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Book price', max_length=3, null=True)),
                ('pages', models.IntegerField(help_text='Number of pages', max_length=3, null=True)),
            ],
        ),
    ]
