# Generated by Django 2.2.2 on 2019-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(help_text='Movie Name', max_length=100, null=True)),
                ('Director', models.CharField(help_text='Director Name', max_length=100, null=True)),
                ('Producer', models.CharField(help_text='Producer Name', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
