# Generated by Django 2.2.2 on 2019-06-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ReleaseDate',
            field=models.DateField(blank=True, null=True, verbose_name='Release'),
        ),
    ]
