# Generated by Django 2.2.2 on 2019-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190619_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(help_text='Student Name', max_length=100, null=True)),
                ('Branch', models.CharField(help_text='Branch', max_length=50, null=True)),
                ('Issued', models.IntegerField(help_text='BooksIssued', max_length=2, null=True)),
            ],
        ),
    ]
