# Generated by Django 2.2.2 on 2019-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Issued',
            field=models.IntegerField(help_text='BooksIssued', null=True),
        ),
    ]
