# Generated by Django 2.2.2 on 2019-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190620_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='Issued',
            new_name='IssuedBooks',
        ),
        migrations.AddField(
            model_name='library',
            name='IssueDate',
            field=models.DateField(null=True, verbose_name='Issued'),
        ),
        migrations.AddField(
            model_name='library',
            name='SubmissionDate',
            field=models.DateField(null=True, verbose_name='Submission'),
        ),
    ]
