# Generated by Django 2.2.2 on 2019-06-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190620_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='Stu_name',
            new_name='Studentname',
        ),
    ]
